language: android
dist: trusty
env:
  global:
  - ANDROID_API=26
  - EMULATOR_API=22
  - ANDROID_BUILD_TOOLS=26.0.2
  - PROJECT_1=RoomWordsWithDelete
  - PACKAGE_NAME=com.android.example.roomwordssample
  
android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  - tools
  - platform-tools

  # The BuildTools version used by your project
  - build-tools-$ANDROID_BUILD_TOOLS

  # The SDK version used to compile your project
  - android-$ANDROID_API
  - android-$EMULATOR_API

  # Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  #- sys-img-x86-android-$EMULATOR_API
  - sys-img-armeabi-v7a-android-$EMULATOR_API

  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+


before_install:
- export PROJECT_ROOT="${PWD}"
- chmod +x ${PROJECT_1}/gradlew
- chmod +x result_parser.py

before_script:
- echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
- emulator -avd test -no-window &
- android-wait-for-emulator
- adb shell settings put global window_animation_scale 0 &
- adb shell settings put global transition_animation_scale 0 &
- adb shell settings put global animator_duration_scale 0 &
- adb shell input keyevent 82 &

script:
- cd ${PROJECT_ROOT}
- cd ${PROJECT_1} && ./gradlew connectedDebugAndroidTest --stacktrace

after_script:
- cd ${PROJECT_ROOT}
- ./result_parser.py ${PROJECT_ROOT}/${PROJECT_1}/app/build/reports/androidTests/connected/${PACKAGE_NAME}.RoomDatabaseTest.html >> results.txt
- echo $(basename ${TRAVIS_REPO_SLUG}) ${TRAVIS_BRANCH} ${TRAVIS_COMMIT} $(git show -s --format=%ci ${TRAVIS_COMMIT} | cut -c 1-20) $(cat results.txt) > results.txt
- awk  '//{for(i=6;i<NF;i=i+2) print $i"\t"$(i+1)}' results.txt
